language: cpp
sudo: required # try trusty with sudo to get more ram
branches:
  only:
    - master
    - s1ap
os:
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
env:
  - COMPILER_VERSION="CC=gcc-4.9 && CXX=g++-4.9" # Use GCC version 4.9
compiler:
  - gcc
before_install:
  - eval "${COMPILER_VERSION}"
  - git clone --depth=1 https://github.com/nsnam/ns-3-dev-git --branch ns-3.24 ns-3.24
  - rm -r ns-3.24/src/lte
  - git clone --depth=1 https://github.com/signetlabdei/lena-plus ns-3.24/src/lte
  - ls ns-3.24/src/lte/
script:
  - cd ns-3.24/
  - ./waf configure --enable-tests --enable-examples && ./waf build
